### Login with d1.andrea@icloud.com
POST http://{{host}}:{{port}}/users/login
Accept: application/json
Content-Type: application/json

{
  "email": "{{andreasEmail}}",
  "password": "{{andreasPassword}}"
}


### Login with john@carmack.com
POST http://{{host}}:{{port}}/users/login
Accept: application/json
Content-Type: application/json

{
  "email": "{{johnsEmail}}",
  "password": "{{johnsPassword}}"
}


### Login with wrong credentials
POST http://{{host}}:{{port}}/users/login
Accept: application/json
Content-Type: application/json

{
  "email": "{{$random.email}}",
  "password": "{{$random.alphanumeric(20)}}"
}

<> 2023-06-26T152138.401.json
<> 2023-06-26T152042.401.json
<> 2023-06-26T152025.401.json
<> 2023-06-26T151914.401.json
<> 2023-06-26T151749.401.json
<> 2023-06-26T151723.401.json
<> 2023-06-26T151640.401.json
<> 2023-06-26T151606.401.json
<> 2023-06-26T151551.401.json
<> 2023-06-26T151531.401.json
<> 2023-06-26T151517.401.json
<> 2023-06-26T151411.401.json
<> 2023-06-26T151346.401.json
<> 2023-06-26T151226.401.json
<> 2023-06-26T151137.401.json
<> 2023-06-26T150855.401.json


### Login with bad formatted request
POST http://{{host}}:{{port}}/users/login
Accept: application/json
Content-Type: application/json

{
  "name": "{{$random.email}}",
  "password": "{{$random.integer(10)}}"
}

<> 2023-06-26T152133.400.json
<> 2023-06-26T151757.400.json


###