### Modify d1.andrea@icloud.com
PUT http://{{host}}:{{port}}/users/{{andreasID}}
Accept: application/json
Content-Type: application/json

{
  "name": "Andrea",
  "surname": "Boccia",
  "email": "d1.andrea@icloud.com",
  "password": "{{$random.alphanumeric(20)}}",
  "roleKey": "wineHQ88"
}

> {%
    client.global.set('andreasPassword', JSON.parse(request.body()).password);
%}