### Get all files
GET http://{{host}}:{{port}}/files
Accept: application/json


### Get files filtering results
GET http://{{host}}:{{port}}/files?maxSize=53754


### Get urandom.txt
GET http://{{host}}:{{port}}/files/{{urandomsID}}
Accept: application/json